services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api.local
    ports:
      - '$PORT:$PORT'
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules

  auto:
    build:
      context: .
      dockerfile: Dockerfile.auto.local
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules

      