services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api.local
    ports:
      - '$PORT:$PORT'
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron.local
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
  work:
    build:
      context: .
      dockerfile: Dockerfile.work.local
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
