services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      - src/web/.env
    ports:
      - "80:80"

  web-local:
    build:
      context: .
      dockerfile: Dockerfile.web.local
    env_file:
      - src/web/.env
    ports:
      - "$PORT:$PORT"
    volumes:
      - ./src/web/.env:/home/node/app/.env
      - ./src/web/.eslint:/home/node/app/.eslint
      - ./src/web/nodemon.json:/home/node/app/nodmeon.json
      - ./src/web/next-env.d.ts:/home/node/app/next-env.d.ts
      - ./src/web/package.json:/home/node/app/package.json
      - ./src/web/node_modules:/home/node/app/node_modules
      - ./src/web/public:/home/node/app/public
      - ./src/web/src:/home/node/app/src

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - src/server/.env
    ports:
      - "80:80"

  api-local:
    build:
      context: .
      dockerfile: Dockerfile.api.local
    env_file:
      - src/server/.env
    ports:
      - "$PORT:$PORT"
    volumes:
      - ./src/server:/home/node/app
      - ./src/server/node_modules:/home/node/app/node_modules

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    env_file:
      - src/server/.env

  cron-local:
    build:
      context: .
      dockerfile: Dockerfile.cron.local
    env_file:
      - src/server/.env
    volumes:
      - ./src/server:/home/node/app
      - ./src/server/node_modules:/home/node/app/node_modules

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - src/server/.env

  worker-local:
    build:
      context: .
      dockerfile: Dockerfile.worker.local
    env_file:
      - src/server/.env
    volumes:
      - ./src/server:/home/node/app
      - ./src/server/node_modules:/home/node/app/node_modules
