apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: readless-web
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers 'x-forwarded-for: $http_x_forwarded_for';
spec:
  tls:
    - hosts:
        - www.readless.ai
      secretName: tls-www.readless.ai
  rules:
    - host: www.readless.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: readless-web-prod
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: readless-web-redirect
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      set $FLAGS "";
      if ($request_uri = '/.well-known/assetlinks.json') {
        set $FLAGS "W";
      }
      if ($host = 'readless.ai') {
        set $FLAGS "${FLAGS}X";
      }
      if ($FLAGS !~ "W") {
        rewrite ^ https://www.readless.ai$request_uri permanent;
      }
spec:
  tls:
    - hosts:
        - readless.ai
      secretName: tls-readless.ai
  rules:
    - host: readless.ai
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: readless-web-prod
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: readless-api
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers 'x-forwarded-for: $http_x_forwarded_for';
spec:
  tls:
    - hosts:
        - api.readless.ai
      secretName: tls-api.readless.ai
  rules:
    - host: api.readless.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: readless-api-prod
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: readless-web-dev
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers 'x-forwarded-for: $http_x_forwarded_for';
    nginx.ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: dev-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
spec:
  tls:
    - hosts:
        - dev.readless.ai
      secretName: tls-dev.readless.ai
  rules:
    - host: dev.readless.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: readless-web-dev
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: readless-api-dev
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers 'x-forwarded-for: $http_x_forwarded_for';
spec:
  tls:
    - hosts:
        - api.dev.readless.ai
      secretName: tls-api.dev.readless.ai
  rules:
    - host: api.dev.readless.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: readless-api-dev
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: motm-web
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - www.mergingoftheminds.com
      secretName: tls-www.mergingoftheminds.com
  rules:
    - host: www.mergingoftheminds.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: readless-web-prod
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: motm-web-redirect
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      set $FLAGS "";
      if ($request_uri = '/.well-known/assetlinks.json') {
        set $FLAGS "W";
      }
      if ($host = 'mergingoftheminds.com') {
        set $FLAGS "${FLAGS}X";
      }
      if ($FLAGS !~ "W") {
        rewrite ^ https://www.mergingoftheminds.com$request_uri permanent;
      }
spec:
  tls:
    - hosts:
        - mergingoftheminds.com
      secretName: tls-mergingoftheminds.com
  rules:
    - host: mergingoftheminds.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: readless-web-prod
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 2nerds1cup-web
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - www.2nerds1cup.com
      secretName: tls-www.2nerds1cup.com
  rules:
    - host: www.2nerds1cup.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: readless-web-prod
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 2nerds1cup-web-redirect
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      set $FLAGS "";
      if ($request_uri = '/.well-known/assetlinks.json') {
        set $FLAGS "W";
      }
      if ($host = '2nerds1cup.com') {
        set $FLAGS "${FLAGS}X";
      }
      if ($FLAGS !~ "W") {
        rewrite ^ https://www.2nerds1cup.com$request_uri permanent;
      }
spec:
  tls:
    - hosts:
        - 2nerds1cup.com
      secretName: tls-2nerds1cup.com
  rules:
    - host: 2nerds1cup.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: readless-web-prod
                port:
                  number: 80