services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "$PORT:$PORT"

  ui-local:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "$PORT:$PORT"
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
