name: Worker CI

on:
  push:
    branches:
      - main
      - dev
    paths:
      - ".github/workflows/work-ci.yaml"
      - "k8s/work-deploy.yaml"
      - "src/server/Dockerfile.work"
      - "src/server/package.json"
      - "src/server/src/work/**"

concurrency:
  group: ${{ github.ref }}-work
  cancel-in-progress: true

env:
  IMAGE: ${{ github.event.repository.name }}-work-${{ fromJSON('{"main":"prod"}')[github.ref_name] || github.ref_name }}
  REGISTRY: ${{ vars.REGISTRY }}
  WORKING_DIR: src/server

jobs:
  build-work:
    runs-on: ubuntu-latest
    environment: ${{ fromJSON('{"main":"prod"}')[github.ref_name] || github.ref_name }}
    steps:
      - name: Print Job Description
        run: |
          echo building \"$IMAGE\" from branch \"${{ github.ref_name }}\"
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.GIT_SSH_KEY }}
          submodules: recursive
      - name: Build
        run: |
          cd $WORKING_DIR && \
          docker build . --file Dockerfile.work --tag $IMAGE:latest
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to doctl
        run: doctl registry login --expiry-seconds 180
      - name: Tag Docker Image
        run: docker tag $IMAGE:latest $REGISTRY/$IMAGE:latest
      - name: Push Docker Image
        run: docker push $REGISTRY/$IMAGE:latest

  deploy-work:
    needs: build-work
    runs-on: ubuntu-latest
    environment: ${{ fromJSON('{"main":"prod"}')[github.ref_name] || github.ref_name }}
    env:
      CORS_ORIGIN: ${{ vars.CORS_ORIGIN }}
      WORKER_FETCH_RATE_LIMIT: ${{ vars.WORKER_FETCH_RATE_LIMIT }}
      WORKER_FETCH_INTERVAL_MS: ${{ vars.WORKER_FETCH_INTERVAL_MS }}
      K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE }}
      K8S_MEMORY_REQUESTS: ${{ vars.K8S_MEMORY_REQUESTS }}
      K8S_CPU_REQUESTS: ${{ vars.K8S_CPU_REQUESTS }}
      K8S_MEMORY_LIMITS: ${{ vars.K8S_MEMORY_LIMITS }}
      K8S_CPU_LIMITS: ${{ vars.K8S_CPU_LIMITS }}
      K8S_REPLICA_COUNT_WORK: ${{ vars.K8S_REPLICA_COUNT_WORK }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PG_CONNECTION_STRING: ${{ secrets.PG_CONNECTION_STRING }}
      PORT: ${{ vars.PORT }}
      RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
      REDIS_CONNECTION_STRING: ${{ secrets.REDIS_CONNECTION_STRING }}
      WORKER_CONCURRENCY: ${{ vars.WORKER_CONCURRENCY }}
      WS_API_KEY: ${{ secrets.WS_API_KEY }}
    steps:
      - name: Print Job Description
        run: |
          echo deploying \"$IMAGE\" from branch \"${{ github.ref_name }}\"
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.GIT_SSH_KEY }}
          submodules: recursive
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Add kubectl cert
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.K8S_CLUSTER_ID }}
      - name: Apply deployment changes
        run: envsubst < $GITHUB_WORKSPACE/k8s/work-deploy.yaml | kubectl apply -f -
      - name: Deploy Rollout
        run: kubectl rollout restart deployment/$IMAGE --namespace $K8S_NAMESPACE
      - name: Verify deployment
        run: kubectl rollout status deployment/$IMAGE --namespace $K8S_NAMESPACE
